#import "PHMetadataStore.h"
#import <UIKit/UIKit.h>

static NSString *PH47FilterPath(void){static NSString *path;static dispatch_once_t once;dispatch_once(&once,^{NSString *home=NSHomeDirectory();NSDirectoryEnumerator *e=[NSFileManager.defaultManager enumeratorAtPath:home];NSString *r=nil;while((r=[e nextObject]))if([r.lastPathComponent.lowercaseString isEqualToString:@"custom-filters.json"]){path=[home stringByAppendingPathComponent:r];break;}if(!path.length)path=[home stringByAppendingPathComponent:@"Documents/custom-filters.json"];});return path;}
static NSMutableArray *PH47LoadFilters(void){NSData*d=[NSData dataWithContentsOfFile:PH47FilterPath()];if(!d)return[NSMutableArray array];id j=[NSJSONSerialization JSONObjectWithData:d options:NSJSONReadingMutableContainers error:nil];if([j isKindOfClass:NSDictionary.class])j=j[@"filters"];return[j isKindOfClass:NSArray.class]?[j mutableCopy]:[NSMutableArray array];}
static NSString *PH47AppName(void){NSString*n=NSBundle.mainBundle.objectForInfoDictionaryKey[@"CFBundleDisplayName"];if(!n.length)n=NSBundle.mainBundle.objectForInfoDictionaryKey[@"CFBundleName"];if(!n.length)n=NSProcessInfo.processInfo.processName;return n.length?n:@"WebHider";}
static NSString *PH47MetadataPath(void){return[PH47FilterPath().stringByDeletingLastPathComponent stringByAppendingPathComponent:[NSString stringWithFormat:@"%@-metadata.json",PH47AppName()]];}
static NSMutableDictionary *PH47LoadMetadata(void){NSData*d=[NSData dataWithContentsOfFile:PH47MetadataPath()];if(!d)return[NSMutableDictionary dictionary];id j=[NSJSONSerialization JSONObjectWithData:d options:NSJSONReadingMutableContainers error:nil];if([j isKindOfClass:NSDictionary.class])j=j[@"elements"];return[j isKindOfClass:NSDictionary.class]?[j mutableCopy]:[NSMutableDictionary dictionary];}
static void PH47WriteMetadata(NSDictionary*e){NSString*p=PH47MetadataPath();if(!e.count){[[NSFileManager defaultManager]removeItemAtPath:p error:nil];return;}NSData*d=[NSJSONSerialization dataWithJSONObject:@{@"version":@1,@"elements":e} options:NSJSONWritingPrettyPrinted|NSJSONWritingSortedKeys error:nil];if(d)[d writeToFile:p atomically:YES];}
static NSString *PH47String(id v){return[v isKindOfClass:NSString.class]?v:@"";}
@implementation PHMetadataStore
+ (void)storeMetadataRecord:(NSDictionary*)record forSelector:(NSString*)selector{if(!selector.length||![record isKindOfClass:NSDictionary.class])return;NSMutableDictionary*m=PH47LoadMetadata();NSMutableDictionary*r=[record mutableCopy];r[@"selector"]=selector;NSString*n=PH47String(r[@"name"]);if(!n.length){NSString*t=PH47String(r[@"text"]);NSString*a=PH47String(r[@"ariaLabel"]);NSString*ti=PH47String(r[@"title"]);NSString*i=PH47String(r[@"id"]);NSString*c=PH47String(r[@"className"]);if(t.length)n=t;else if(a.length)n=a;else if(ti.length)n=ti;else if(i.length)n=[NSString stringWithFormat:@"#%@",i];else if(c.length)n=[c componentsSeparatedByString:@" "][0];else n=selector;}r[@"name"]=n;m[selector]=r;PH47WriteMetadata(m);}
+ (void)storeMetadataRecords:(NSArray<NSDictionary*>*)records{NSMutableDictionary*m=PH47LoadMetadata();for(NSDictionary*record in records){if(![record isKindOfClass:NSDictionary.class])continue;NSString*s=PH47String(record[@"selector"]);if(!s.length)continue;NSMutableDictionary*r=[record mutableCopy];r[@"selector"]=s;NSString*n=PH47String(r[@"name"]);if(!n.length){NSString*t=PH47String(r[@"text"]);NSString*a=PH47String(r[@"ariaLabel"]);NSString*ti=PH47String(r[@"title"]);NSString*i=PH47String(r[@"id"]);NSString*c=PH47String(r[@"className"]);if(t.length)n=t;else if(a.length)n=a;else if(ti.length)n=ti;else if(i.length)n=[NSString stringWithFormat:@"#%@",i];else if(c.length)n=[c componentsSeparatedByString:@" "][0];else n=s;}r[@"name"]=n;m[s]=r;}PH47WriteMetadata(m);}
+ (void)synchronizeWithFilters{NSArray*filters=PH47LoadFilters();NSMutableSet*active=[NSMutableSet set];for(NSDictionary*f in filters){NSString*s=PH47String(f[@"selector"]);if(s.length)[active addObject:s];else{NSDictionary*a=f[@"action"];NSString*z=PH47String(a[@"selector"]);if(z.length)[active addObject:z];}}NSMutableDictionary*old=PH47LoadMetadata();NSMutableDictionary*out=[NSMutableDictionary dictionary];for(NSString*k in old){NSDictionary*r=old[k];NSString*rs=PH47String(r[@"selector"]);BOOL keep=[active containsObject:k]||[active containsObject:rs];if(!keep){NSString*cls=PH47String(r[@"className"]);NSString*rid=PH47String(r[@"id"]);for(NSString*a in active){if([a hasPrefix:@"."]&&[[cls componentsSeparatedByString:@" "]containsObject:[a substringFromIndex:1]]){keep=YES;break;}if([a hasPrefix:@"#"]&&[rid isEqualToString:[a substringFromIndex:1]]){keep=YES;break;}}}if(keep){NSString*key=[active containsObject:k]?k:nil;if(!key&&[active containsObject:rs])key=rs;if(!key){NSString*cls=PH47String(r[@"className"]);NSString*rid=PH47String(r[@"id"]);for(NSString*a in active){if([a hasPrefix:@"."]&&[[cls componentsSeparatedByString:@" "]containsObject:[a substringFromIndex:1]]){key=a;break;}if([a hasPrefix:@"#"]&&[rid isEqualToString:[a substringFromIndex:1]]){key=a;break;}}}out[key?:k]=r;}}PH47WriteMetadata(out);}
+ (void)replaceMetadataSelector:(NSString*)oldSelector withSelector:(NSString*)newSelector{if(!oldSelector.length||!newSelector.length||[oldSelector isEqualToString:newSelector])return;NSMutableDictionary*m=PH47LoadMetadata();NSDictionary*r=m[oldSelector];if(r){NSMutableDictionary*n=[r mutableCopy];n[@"selector"]=newSelector;m[newSelector]=n;[m removeObjectForKey:oldSelector];PH47WriteMetadata(m);}}
+ (NSString*)nameForSelector:(NSString*)selector{NSDictionary*r=PH47LoadMetadata()[selector];NSString*n=PH47String(r[@"name"]);if(n.length)return n;if([selector hasPrefix:@"."]||[selector hasPrefix:@"#"]){NSString*needle=[selector substringFromIndex:1];for(NSDictionary*x in PH47LoadMetadata().allValues){if([selector hasPrefix:@"."]&&[[PH47String(x[@"className"])componentsSeparatedByString:@" "]containsObject:needle])return PH47String(x[@"name"]);if([selector hasPrefix:@"#"]&&[PH47String(x[@"id"])isEqualToString:needle])return PH47String(x[@"name"]);}}return nil;}
@end
