#import "PHMetadataStore.h"

static NSString *PH48FilterPath(void){static NSString*p;static dispatch_once_t once;dispatch_once(&once,^{NSString*home=NSHomeDirectory();NSDirectoryEnumerator*e=[NSFileManager.defaultManager enumeratorAtPath:home];NSString*r=nil;while((r=[e nextObject]))if([r.lastPathComponent.lowercaseString isEqualToString:@"custom-filters.json"]){p=[home stringByAppendingPathComponent:r];break;}if(!p.length)p=[home stringByAppendingPathComponent:@"Documents/custom-filters.json"];});return p;}
static NSString *PH48MetadataPath(void){static NSString*p;static dispatch_once_t once;dispatch_once(&once,^{NSString*n=NSBundle.mainBundle.objectForInfoDictionaryKey[@"CFBundleDisplayName"];if(![n isKindOfClass:NSString.class]||!n.length)n=NSBundle.mainBundle.objectForInfoDictionaryKey[@"CFBundleName"];if(![n isKindOfClass:NSString.class]||!n.length)n=NSProcessInfo.processInfo.processName;if(![n isKindOfClass:NSString.class]||!n.length)n=@"WebHider";p=[PH48FilterPath().stringByDeletingLastPathComponent stringByAppendingPathComponent:[NSString stringWithFormat:@"%@-metadata.json",n]];});return p;}
static NSMutableDictionary*PH48Load(void){NSData*d=[NSData dataWithContentsOfFile:PH48MetadataPath()];if(!d)return[NSMutableDictionary dictionary];id r=[NSJSONSerialization JSONObjectWithData:d options:NSJSONReadingMutableContainers error:nil];if([r isKindOfClass:NSDictionary.class]&&[r[@"elements"] isKindOfClass:NSDictionary.class])r=r[@"elements"];return[r isKindOfClass:NSDictionary.class]?[r mutableCopy]:[NSMutableDictionary dictionary];}
static void PH48Write(NSDictionary*e){NSString*p=PH48MetadataPath();if(!e.count){[NSFileManager.defaultManager removeItemAtPath:p error:nil];return;}[[NSFileManager defaultManager]createDirectoryAtPath:p.stringByDeletingLastPathComponent withIntermediateDirectories:YES attributes:nil error:nil];NSData*d=[NSJSONSerialization dataWithJSONObject:@{@"version":@1,@"elements":e} options:NSJSONWritingPrettyPrinted|NSJSONWritingSortedKeys error:nil];if(d)[d writeToFile:p atomically:YES];}
static NSMutableDictionary*PH48Pending(void){static NSMutableDictionary*p;static dispatch_once_t once;dispatch_once(&once,^{p=[NSMutableDictionary dictionary];});return p;}
static NSString*PH48S(id v,NSUInteger m){if(![v isKindOfClass:NSString.class])return nil;NSString*s=[(NSString*)v stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];return s.length>m?[s substringToIndex:m]:s;}
static NSString*PH48Name(NSDictionary*r){NSString*n=PH48S(r[@"name"],120);if(n.length)return n;NSString*t=PH48S(r[@"tag"],40),*i=PH48S(r[@"id"],160),*x=PH48S(r[@"text"],500),*a=PH48S(r[@"ariaLabel"],300),*title=PH48S(r[@"title"],300),*c=PH48S(r[@"className"],300);if([t isEqualToString:@"lottie-player"])return@"Lottie Player";if(a.length)return a;if(x.length)return x;if(title.length)return title;if(i.length)return[@"#" stringByAppendingString:i];for(NSString*q in[c componentsSeparatedByString:@" "])if(q.length&&![q hasPrefix:@"ng-"]&&![q hasPrefix:@"css-"]&&![q hasPrefix:@"sc-"]&&![q hasPrefix:@"jsx-"]&&![q isEqualToString:@"active"]&&![q isEqualToString:@"selected"]&&![q isEqualToString:@"disabled"])return q;return t.uppercaseString.length?t.uppercaseString:@"Elemento Web";}
static NSString*PH48Selector(NSDictionary*f){if(![f isKindOfClass:NSDictionary.class])return nil;NSString*s=f[@"selector"];if(![s isKindOfClass:NSString.class]||!s.length){NSDictionary*a=f[@"action"];s=[a isKindOfClass:NSDictionary.class]?a[@"selector"]:nil;}return[s isKindOfClass:NSString.class]&&s.length?s:nil;}
@implementation PHMetadataStore
+ (void)recordMetadata:(NSDictionary*)metadata forSelector:(NSString*)selector{if(!selector.length||![metadata isKindOfClass:NSDictionary.class])return;NSMutableDictionary*r=[metadata mutableCopy];r[@"selector"]=selector;NSString*n=PH48Name(r);r[@"name"]=[n substringToIndex:MIN(n.length,120)];@synchronized(PH48Pending()){PH48Pending()[selector]=r;}}
+ (void)migrateMetadataFromSelector:(NSString*)oldSelector toSelector:(NSString*)newSelector{if(!oldSelector.length||!newSelector.length||[oldSelector isEqualToString:newSelector])return;NSMutableDictionary*all=PH48Load();NSDictionary*r=all[oldSelector];if(![r isKindOfClass:NSDictionary.class])return;NSMutableDictionary*copy=[r mutableCopy];copy[@"selector"]=newSelector;all[newSelector]=copy;[all removeObjectForKey:oldSelector];PH48Write(all);}
+ (void)synchronizeWithFilters{NSData*d=[NSData dataWithContentsOfFile:PH48FilterPath()];id root=d?[NSJSONSerialization JSONObjectWithData:d options:NSJSONReadingMutableContainers error:nil]:nil;NSArray*filters=[root isKindOfClass:NSDictionary.class]?[root[@"filters"] isKindOfClass:NSArray.class]?root[@"filters"]:@[]:[root isKindOfClass:NSArray.class]?root:@[];NSMutableDictionary*out=[NSMutableDictionary dictionary];NSDictionary*saved=PH48Load();NSMutableDictionary*pending=[NSMutableDictionary dictionary];@synchronized(PH48Pending()){[pending addEntriesFromDictionary:PH48Pending()];}for(NSDictionary*f in filters){NSString*s=PH48Selector(f);if(!s.length)continue;NSDictionary*found=nil;for(NSString*k in saved){NSDictionary*r=saved[k];if([k isEqualToString:s]||[PH48S(r[@"selector"],1200)isEqualToString:s]){found=r;break;}}if(!found)for(NSString*k in pending){NSDictionary*r=pending[k];if([k isEqualToString:s]||[PH48S(r[@"selector"],1200)isEqualToString:s]){found=r;break;}}if(found)out[s]=found;}@synchronized(PH48Pending()){[PH48Pending()removeAllObjects];}PH48Write(out);}
+ (NSString*)nameForSelector:(NSString*)selector{if(!selector.length)return nil;NSDictionary*all=PH48Load();NSDictionary*r=all[selector];NSString*n=PH48S(r[@"name"],120);if(n.length)return n;if([selector hasPrefix:@"."]||[selector hasPrefix:@"#"]){NSString*needle=[selector substringFromIndex:1];for(NSDictionary*x in all.allValues){if([selector hasPrefix:@"#"]&&[PH48S(x[@"id"],160)isEqualToString:needle])return PH48S(x[@"name"],120);if([selector hasPrefix:@"."]&&[[PH48S(x[@"className"],300)componentsSeparatedByString:@" "]containsObject:needle])return PH48S(x[@"name"],120);}}return nil;}
@end
