#import "PHMetadataStore.h"
#import <WebKit/WebKit.h>
#import <objc/runtime.h>

static NSString *PHV21FilterPath(void){static NSString*p;static dispatch_once_t once;dispatch_once(&once,^{NSString*home=NSHomeDirectory();NSDirectoryEnumerator*e=[NSFileManager.defaultManager enumeratorAtPath:home];NSString*r=nil;while((r=[e nextObject]))if([r.lastPathComponent.lowercaseString isEqualToString:@"custom-filters.json"]){p=[home stringByAppendingPathComponent:r];break;}if(!p.length)p=[home stringByAppendingPathComponent:@"Documents/custom-filters.json"];});return p;}
static NSString *PHV21SelectorFromFilter(NSDictionary*f){if(![f isKindOfClass:NSDictionary.class])return nil;NSString*s=f[@"selector"];if(![s isKindOfClass:NSString.class]||!s.length){NSDictionary*a=f[@"action"];s=[a isKindOfClass:NSDictionary.class]?a[@"selector"]:nil;}return[s isKindOfClass:NSString.class]&&s.length?s:nil;}
static NSDictionary *PHV21NativeFilter(NSDictionary*f,NSString*stable){NSString*s=PHV21SelectorFromFilter(f);if(!s.length)return nil;if(stable.length)s=stable;return @{@"selector":s};}
static NSString *PHV21StableSelectorScript(void){return @"(function(){var e=document.querySelector('[data-projetoh-selected=\\\"1\\\"]');if(!e)return '';if(e.id)return '#'+CSS.escape(e.id);var c=(typeof e.className==='string'?e.className:'').trim().split(/\\s+/).filter(function(x){return x.length&&!/^ng-|^css-|^sc-|^jsx-/.test(x)&&x!=='active'&&x!=='selected'&&x!=='disabled';});if(c.length)return '.'+CSS.escape(c[0]);return '';})()";}
static void PHV21NormalizeSavedFilters(NSString*stable){NSString*path=PHV21FilterPath();NSData*data=[NSData dataWithContentsOfFile:path];if(!data)return;id root=[NSJSONSerialization JSONObjectWithData:data options:NSJSONReadingMutableContainers error:nil];NSArray*filters=nil;if([root isKindOfClass:NSDictionary.class])filters=[root[@"filters"] isKindOfClass:NSArray.class]?root[@"filters"]:nil;else if([root isKindOfClass:NSArray.class])filters=root;if(!filters)return;NSMutableArray*native=[NSMutableArray arrayWithCapacity:filters.count];for(NSUInteger i=0;i<filters.count;i++){NSString*oldSelector=PHV21SelectorFromFilter(filters[i]);NSDictionary*c=PHV21NativeFilter(filters[i],i==filters.count-1?stable:nil);if(c)[native addObject:c];NSString*newSelector=PHV21SelectorFromFilter(c);if(i==filters.count-1&&stable.length&&oldSelector.length&&newSelector.length&&![oldSelector isEqualToString:newSelector])[PHMetadataStore migrateMetadataFromSelector:oldSelector toSelector:newSelector];}NSData*out=[NSJSONSerialization dataWithJSONObject:native options:NSJSONWritingPrettyPrinted|NSJSONWritingSortedKeys error:nil];if(out)[out writeToFile:path atomically:YES];}
static IMP PHV21OriginalSave=nil;
static void PHV21SavePendingFilters(id self,SEL _cmd){if(PHV21OriginalSave)((void(*)(id,SEL))PHV21OriginalSave)(self,_cmd);WKWebView*webView=nil;@try{webView=[self valueForKey:@"highlightedWebView"];}@catch(__unused NSException*e){}if(![webView isKindOfClass:WKWebView.class]){PHV21NormalizeSavedFilters(nil);return;}[webView evaluateJavaScript:PHV21StableSelectorScript() completionHandler:^(id result,NSError*error){NSString*stable=(!error&&[result isKindOfClass:NSString.class]&&[(NSString*)result length])?result:nil;PHV21NormalizeSavedFilters(stable);}];}
__attribute__((constructor))static void PHV21Install(void){dispatch_async(dispatch_get_main_queue(),^{Class cls=NSClassFromString(@"PHOverlayManager");if(!cls)return;Method method=class_getInstanceMethod(cls,@selector(savePendingFilters));if(!method)return;IMP current=method_getImplementation(method);if(current==(IMP)PHV21SavePendingFilters)return;PHV21OriginalSave=current;method_setImplementation(method,(IMP)PHV21SavePendingFilters);});}
